### ISSUE TITLE
Non-Deterministic Outputs

### ISSUE THREAD

**Issue by MDFL64** [Redcrafter/verilog2factorio#10]
Compiling the same file twice does not necessarily produce the same results. This may make it difficult to reproduce or debug errors.

I assume the culprit is the randomness in the simulator. Maybe using a static seed would help?

**Comment by Redcrafter** [comment]
Yeah by default node does not allow for seeded random number generation. Fixed with 53d64dd

**Comment by justchen1369** [comment]
imo it should be seeding it with a random seed by default, and allowing one to specify the seed as a command line flag.
