### ISSUE TITLE
Attempts to Construct Overlong Wires

### ISSUE THREAD

**Issue by MDFL64** [Redcrafter/verilog2factorio#11]
In some cases the compiler might try to construct overlong wires. 

I have two guesses for why this might be happening:
- This only happens for constant combinators. Since they don't line up with the normal "grid" of 2x1 combinators, the assumptions about distance can be wrong.
- This only happens for input/output nodes. I don't think this is very likely from what I have seen of the code.

Image of an affected blueprint (with some combinators removed for clarity).
![screenshot](http://tmp.bz/2ue86YAXjft.png)

I've double-checked that these wires can't be constructed in-game.
![screenshot](http://tmp.bz/2udrUp1Ge6K.png)

Blueprint:
https://gist.github.com/birdbrainswagtrain/b719b2c88bda39aa7a40ba6e5ceb9333

**Comment by Redcrafter** [comment]
Does the compiler report simulation errors?

**Comment by justchen1369** [comment]
Simulation errors should enumerate overlong wires.

**Comment by MDFL64** [comment]
Alright. I was under the impression that it was supposed to continue iterating if it encountered any errors, but this was apparently disabled? I re-enabled the iteration then fed my file through it with a bunch of different seeds. I didn't run into the issue again as far as I could tell, so I guess I'll close this for now.

**Comment by justchen1369** [comment]
it seems that https://github.com/Redcrafter/verilog2factorio/commit/2ef2b9dcf3c9d7dd6822e1956fb6cbbeae1a0633 broke the iterating.
